Code/New_Open_Schooling/New_Open_Schooling/Controllers/StateController.cs
using New_Open_Schooling.Helper;
using New_Open_Schooling.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace New_Open_Schooling.Controllers
{
    public class StateController : Controller
    {
        Open_Schooling_Final_2023Entities1 db = new Open_Schooling_Final_2023Entities1();
        Common common = new Common();
        // GET: State
        public ActionResult StateLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult StateLogin(State_Login_Model state_Login_Model)
        {
            try
            {
                if(state_Login_Model.User_Name == "admin" && state_Login_Model.State_Password =="admin")
                {
                    return RedirectToAction("StateDashboard");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid Details.");
                  
                    return View();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
          
        }

        public ActionResult StateDashboard()
        {
            string count = "";
            count = "select count( * ) as countData from Tbl_Registration a join tbl_payment b on  a.ApplicationId = b.merchant_param1 and b.order_status = 'success'  and a.Payment_Status = '1'";
            List<Division_List_Model> model = db.Database.SqlQuery<Division_List_Model>(count).ToList();
            foreach (var item in model)
            {
                TempData["count"] ="Total Registered Students are  "+ item.countData;
            }
            
            return View();
        }
        [HttpPost]
        public ActionResult StateDashboard(string Div_Code, string Excel)
        {
            string Query = "", fileName = "";
            try
            {

                
                Query = "select * from Tbl_Registration A join Center_Login_Information B on A.Center_Code=B.Contact_Center_Code join Tbl_payment P on A.ApplicationId=P.merchant_param1 where B.Div_Code='" + Div_Code + "'and A.Payment_Status='1' and P.order_status='Success' ";
                //Query = "select * from Tbl_Registration A join Center_Login_Information B on A.Center_Code=B.Contact_Center_Code where B.Div_Code='" + Div_Code + "'and A.Payment_Status='1' ";
                List<Division_List_Model> model = db.Database.SqlQuery<Division_List_Model>(Query).ToList();
               

                if (Excel == "1")
                {
                    DataTable dt = common.ToDataTable(model);
                    dt.TableName = "District_Batch_List";
                    fileName = DateTime.Now.Day.ToString() + DateTime.Now.Month.ToString() + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString() + "District_Batch_List";
                    common.CreateExcelFile(dt, fileName);

                }
                return Json(new { Result = true, Response = model, FileName = fileName }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                return Json(new { Result = true, Response ="Unable to Fetch Record", }, JsonRequestBehavior.AllowGet);
            }
          
        }
        public ActionResult Download_State_Record()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult Download_State_Record(string Div_Code,string Excel)
        {
            string Query = "", fileName = "";
            try
                {
                    List<Division_List_Model> centerViewModel = new List<Division_List_Model>();
                   if(Div_Code=="1")
                   {
                    Query = "select * from Tbl_Registration A join Tbl_payment P on A.ApplicationId=P.merchant_param1 where  A.Payment_Status='1' and P.order_status='Success' ";
                    
                    List<Division_List_Model> model = db.Database.SqlQuery<Division_List_Model>(Query).ToList();
                    if (Excel == "1")
                    {
                        DataTable dt = common.ToDataTable(model);
                        dt.TableName = "State_Registered_List";
                        fileName = DateTime.Now.Day.ToString() + DateTime.Now.Month.ToString() + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString() + "District_Batch_List";
                        common.CreateExcelFile(dt, fileName);

                    }
                    return Json(new { Result = true, Response = model, FileName = fileName }, JsonRequestBehavior.AllowGet);
                  
                }
                else
                   if(Div_Code=="2")
                   {
                    Query = "select * from Tbl_Registration A join Tbl_payment P on A.ApplicationId=P.merchant_param1 where  A.Payment_Status='1' and P.order_status='Success' and A.Ec_Status='Completed'";

                    List<Division_List_Model> model = db.Database.SqlQuery<Division_List_Model>(Query).ToList();
                    if (Excel == "1")
                    {
                        DataTable dt = common.ToDataTable(model);
                        dt.TableName = "State_Registered_List";
                        fileName = DateTime.Now.Day.ToString() + DateTime.Now.Month.ToString() + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString() + "District_Batch_List";
                        common.CreateExcelFile(dt, fileName);

                    }
                    return Json(new { Result = true, Response = model, FileName = fileName }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    Query = "select * from Tbl_Registration A join Tbl_payment P on A.ApplicationId=P.merchant_param1 where  A.Payment_Status='1' and P.order_status='Success' and A.Hall_Ticket='1'";

                    List<Division_List_Model> model = db.Database.SqlQuery<Division_List_Model>(Query).ToList();
                    if (Excel == "1")
                    {
                        DataTable dt = common.ToDataTable(model);
                        dt.TableName = "State_Registered_List";
                        fileName = DateTime.Now.Day.ToString() + DateTime.Now.Month.ToString() + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString() + "District_Batch_List";
                        common.CreateExcelFile(dt, fileName);

                    }
                    return Json(new { Result = true, Response = model, FileName = fileName }, JsonRequestBehavior.AllowGet);
                }

                   

               
                //centerViewModel.AddRange(centerViewModel);
                return Json(new { Result = true, Response = centerViewModel, FileName = fileName }, JsonRequestBehavior.AllowGet);
            }
                catch (Exception ex)
                {
                return Json(new { Result = false, Response = "",  }, JsonRequestBehavior.AllowGet);
            }
           
        }
    }
}

Code/New_Open_Schooling/New_Open_Schooling/Views/State/Download_State_Record.cshtml
@model New_Open_Schooling.Models.Division_List_Model
@{
    ViewBag.Title = "Download_State_Record";
    Layout = "~/Views/Shared/Center_Layout.cshtml";
}

<style>

    table, th, td {
        border: 1px solid #c1d0d9b8;
        border-collapse: collapse;
    }

    th, td {
        padding: 5px;
    }

    table {
        display: block;
        overflow-x: auto;
        white-space: nowrap;
    }


    #btn_Excel {
        width: 200px;
        padding: 8px;
        position: absolute;
        right: 20px;
    }
</style>

@*<style>


    table, th, td {
        border: 1px solid #000000;
        border-collapse: collapse;
    }

    th, td {
        padding: 5px;
    }

    table {
       /* display: block;
        overflow-x: auto;
        white-space: nowrap;*/
    }


    #btn_Excel {
        width: 200px;
        padding: 8px;
        position: absolute;
        right: 20px;
    }
</style>*@
<div class="row">
    <div class="col-sm-6">
        <h2>StateDashboard</h2>
    </div>
    <div class="col-sm-6">



        <h2></h2>
        <input type="button" class="btn btn-success" id="btn_Excel" value="Download Excel"><br />
    </div>
</div>
<div class="row">
    <div style="float:right;  margin-right:50px;padding-top:10px;color:red;font-size:18px;">
      
    </div>
</div>
<br />
<div class="row" style="border:inset 2px  #3eadcf"></div>
<br />
<form id="batch_form">

    <div class="row">

        <center>
            <div class="col-sm-2">
                <label>Select Type :</label>
                @Html.DropDownListFor(m => m.Div_Code, new List<SelectListItem> {
                new SelectListItem { Text = "Select Type",   Value = "0", Selected = true,Disabled = true},
                new SelectListItem{Text="Registration Form", Value="1"},
                new SelectListItem{Text="Download EC", Value="2"},
                new SelectListItem{Text="Download Hall Ticket", Value="3"},

                }, new { @name = "Type", @class = "form-control" })
            </div>

        </center>
    </div>

    <br />
    <br />
    <br />
    <center>
        @*<table class="table " id="tbl_list" style="background-color: #e7fafe;"></table>*@
            <table class="AppFormTable" id="tbl_list" style="background-color: #e7fafe;"></table>
    </center>
</form>

@*<div class="container">
        <div class="col-sm-2 dropdown" style=" margin-left:800px; margin-top:30px; ">
            <label style="margin-right:30px;">Select Type :</label>
            <div>
                <button class="form-control">Select  Type</button>
                <div class="dropdown-content">
                    <a id="register">Registration Form</a>
                    <a id="EC">Download EC</a>
                    <a id="HallTicket">Download Hall Ticket</a>
                </div>
            </div>
        </div>
    </div>*@








<script>

    $("#Div_Code").change(function () {

        Get_Inspection_Record("0");

    });
    $("#btn_Excel").click(function () {

        Get_Inspection_Record("1");

    });
    function Get_Inspection_Record(Excel) {
        $.ajax({
            url: 'Download_State_Record',
            type: 'Post',
            dataType: 'Json',
            data: {
                Div_Code: $("#Div_Code").val(),

                Excel: Excel
            },
            success: function (data) {

                var temp = "";
                temp += `<thead>     <tr><td>Sr.No.</td>                            <td>Enrollment_No</td>               <td>ApplicationId </td>               <td> First_Name</td>            <td>Middle_Name </td>          <td> Last_Name</td>           <td>Mother_Name </td>            <td>Adhar_no </td>          <td> Mobile_No</td>             <td>Address </td>          <td>Village </td>             <td>District </td>              <td>Taluka </td>             <td>State </td>         <td>Pin_Code </td>            <td>Date_of_Birth </td           ><td>DOB_Words </td>           <td>DOB_Village </td>            <td>DOB_Taluka </td>         <td> DOB_District</td>                <td>Email </td>               <td> Gender</td>         <td> Standard</td>               <td>Medium </td>     <td>District_Center </td>               <td> Taluka_Center</td>             <td> Center</td>                 <td>Center_Code </td>               <td> Previous_Attend_School_YN </td>      <td> Previous_Attend_School </td>         <td>Handicap  </td>       <td> Candidate_Handicaped_YN </td>                  <td> Subject_List </td>             <td>Minority_Religion  </td>           <td>Nsqf_Subject  </td>     <td> Password </td>               <td> Payment_Status </td>    <td> DateNow </td></tr></thead><tbody`;
                if (data.Result) {
                    $("#tbl_list").empty();
                    $.each(data.Response, function (i, data) {
                        temp += `<tr><td>` + (i + 1) + `</td><td>` + data.Enrollment_No + `</td><td>` + data.ApplicationId + `</td><td>` + data.First_Name + `</td><td>` + data.Middle_Name + `</td><td>` + data.Last_Name + `</td><td>` + data.Mother_Name + `</td><td>` + data.Adhar_no + `</td><td>` + data.Mobile_No + `</td><td>` + data.Address + `</td><td>` + data.Village + `</td><td>` + data.District + `</td><td>` + data.Taluka + `</td><td>` + data.State + `</td><td>` + data.Pin_Code + `</td><td>` + data.Date_of_Birth + `</td><td>` + data.DOB_Words + `</td><td>` + data.DOB_Village + `</td><td>` + data.DOB_Taluka + `</td><td>` + data.DOB_District + `</td><td>` + data.Email + `</td><td>` + data.Gender + `</td><td>` + data.Standard + `</td><td>` + data.Medium + `</td><td>` + data.District_Center + `</td><td>` + data.Taluka_Center + `</td><td>` + data.Center + `</td><td>` + data.Center_Code + `</td><td>` + data.Previous_Attend_School_YN + `</td><td>` + data.Previous_Attend_School + `</td><td>` + data.Handicap + `</td><td>` + data.Candidate_Handicaped_YN + `</td><td>` + data.Subject_List + `</td><td>` + data.Minority_Religion + `</td><td>` + data.Nsqf_Subject + `</td><td>` + data.Password + `</td><td>` + data.Payment_Status + `</td><td>` + data.DateNow + `</td></tr>`;
                    });
                    temp += `</tbody>`;
                    $("#tbl_list").append(temp);

                    if (Excel == "1") {

                        window.location.href = "../State/" + data.FileName + ".xlsx";

                    }
                }
            },
            //success: function (data) {

            //    var temp = "";
            //    temp += `<thead>     <tr><td>Sr.No.</td>        <td>ApplicationId </td>      <td> First_Name</td>  <td> Last_Name</td>                 <td>Mobile_No </td>    </tr></thead><tbody`;
            //    if (data.Result) {
            //        $("#tbl_list").empty();
            //        $.each(data.Response, function (i, data) {
            //            temp += `<tr><td>` + (i + 1) + `</td><td>` + data.ApplicationId + `</td><td>` + data.Name + `</td><td>` + data.Last_Name + `</td><td>` + data.Mobile_No + `</td></tr>`;
            //        });
            //        temp += `</tbody>`;
            //        $("#tbl_list").append(temp);

            //        if (Excel == "1") {

            //            window.location.href = "../State/" + data.FileName + ".xlsx";

            //        }
            //    }
            //},
        });
    }
</script>

Code/New_Open_Schooling/New_Open_Schooling/Views/State/StateDashboard.cshtml
@model New_Open_Schooling.Models.Division_List_Model
@{
    ViewBag.Title = "StateDashboard";
    Layout = "~/Views/Shared/LoginLayout.cshtml";
}

<style>

    table, th, td {
        border: 1px solid #c1d0d9b8;
        border-collapse: collapse;
    }

    th, td {
        padding: 5px;
    }

    table {
        display: block;
        overflow-x: auto;
        white-space: nowrap;
    }


    #btn_Excel {
        width: 200px;
        padding: 8px;
        position: absolute;
        right: 20px;
    }
</style>

<div class="row">
    <div class="col-sm-6">
        <h2>StateDashboard</h2>
    </div>
    <div class="col-sm-6">



        <h2></h2>
        <input type="button" class="btn btn-success" id="btn_Excel" value="Download Excel"><br />
    </div>
</div>
<div class="row">
    <div  style="float:right;  margin-right:50px;padding-top:10px;color:red;font-size:18px;">
        @TempData["count"].ToString()
    </div>
</div>
    <br />
    <div class="row" style="border:inset 2px  #3eadcf"></div>
    <br />
    <form id="batch_form">

        <div class="row">




            <div class="col-sm-2">
                <label>Select Division :</label>
                @Html.DropDownListFor(m => m.Div_Code, new List<SelectListItem> {
                new SelectListItem { Text = "Select Division",   Value = "0", Selected = true,Disabled = true},
                new SelectListItem{Text="PUNE", Value="1"},
                new SelectListItem{Text="NAGPUR", Value="2"},
                new SelectListItem{Text="AURANGABAD", Value="3"},
                new SelectListItem{Text="MUMBAI", Value="4"},
                new SelectListItem{Text="KOLHAPUR", Value="5"},
                new SelectListItem{Text="AMRAVATI", Value="6"},
                new SelectListItem{Text="NASHIK", Value="7"},
                new SelectListItem{Text="LATUR", Value="8"},
                new SelectListItem{Text="KONKAN ", Value="9"},
                }, new { @name = "Type", @class = "form-control" })
            </div>
            @*<div class="col-sm-2">
                    <label></label><br />
                    <input type="button" class="btn btn-success" id="btn_submit" value="Submit">
                </div>*@
        </div>


        <br />
        <br />
        <center>
            <table class="AppFormTable" id="tbl_list" style="background-color: #e7fafe;"></table>
        </center>
    </form>

    <script>

        $("#Div_Code").change(function () {

            Get_Inspection_Record("0");

        });
        $("#btn_Excel").click(function () {

            Get_Inspection_Record("1");

        });
        function Get_Inspection_Record(Excel) {
            $.ajax({
                type: 'POST',
                url: '../State/StateDashboard',
                dataType: 'json',
                data: {
                    Div_Code: $("#Div_Code").val(),

                    Excel: Excel
                },
                beforeSend: function () {
                    Showloader();
                },
                complete: function () {
                    Hideloader();
                },
                success: function (data) {

                    var temp = "";
                    temp += `<thead>     <tr><td>Sr.No.</td>                            <td>Enrollment_No</td>               <td>ApplicationId </td>               <td> First_Name</td>            <td>Middle_Name </td>          <td> Last_Name</td>           <td>Mother_Name </td>            <td>Adhar_no </td>          <td> Mobile_No</td>             <td>Address </td>          <td>Village </td>             <td>District </td>              <td>Taluka </td>             <td>State </td>         <td>Pin_Code </td>            <td>Date_of_Birth </td           ><td>DOB_Words </td>           <td>DOB_Village </td>            <td>DOB_Taluka </td>         <td> DOB_District</td>                <td>Email </td>               <td> Gender</td>         <td> Standard</td>               <td>Medium </td>     <td>District_Center </td>               <td> Taluka_Center</td>             <td> Center</td>                 <td>Center_Code </td>               <td> Previous_Attend_School_YN </td>      <td> Previous_Attend_School </td>         <td>Handicap  </td>       <td> Candidate_Handicaped_YN </td>                  <td> Subject_List </td>             <td>Minority_Religion  </td>           <td>Nsqf_Subject  </td>     <td> Password </td>               <td> Payment_Status </td>    <td> DateNow </td></tr></thead><tbody`;
                    if (data.Result) {
                        $("#tbl_list").empty();
                        $.each(data.Response, function (i, data) {
                            temp += `<tr><td>` + (i + 1) + `</td><td>` + data.Enrollment_No + `</td><td>` + data.ApplicationId + `</td><td>` + data.First_Name + `</td><td>` + data.Middle_Name + `</td><td>` + data.Last_Name + `</td><td>` + data.Mother_Name + `</td><td>` + data.Adhar_no + `</td><td>` + data.Mobile_No + `</td><td>` + data.Address + `</td><td>` + data.Village + `</td><td>` + data.District + `</td><td>` + data.Taluka + `</td><td>` + data.State + `</td><td>` + data.Pin_Code + `</td><td>` + data.Date_of_Birth + `</td><td>` + data.DOB_Words + `</td><td>` + data.DOB_Village + `</td><td>` + data.DOB_Taluka + `</td><td>` + data.DOB_District + `</td><td>` + data.Email + `</td><td>` + data.Gender + `</td><td>` + data.Standard + `</td><td>` + data.Medium + `</td><td>` + data.District_Center + `</td><td>` + data.Taluka_Center + `</td><td>` + data.Center + `</td><td>` + data.Center_Code + `</td><td>` + data.Previous_Attend_School_YN + `</td><td>` + data.Previous_Attend_School + `</td><td>` + data.Handicap + `</td><td>` + data.Candidate_Handicaped_YN + `</td><td>` + data.Subject_List + `</td><td>` + data.Minority_Religion + `</td><td>` + data.Nsqf_Subject + `</td><td>` + data.Password + `</td><td>` + data.Payment_Status + `</td><td>` + data.DateNow + `</td></tr>`;
                        });
                        temp += `</tbody>`;
                        $("#tbl_list").append(temp);

                        if (Excel == "1") {

                            window.location.href = "../State/" + data.FileName + ".xlsx";

                        }
                    }
                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
        }

    </script>

Code/New_Open_Schooling/New_Open_Schooling/Views/State/StateLogin.cshtml
@model New_Open_Schooling.Models.State_Login_Model
@{
    ViewBag.Title = "StateLogin";
    Layout = "~/Views/Shared/LoginLayout.cshtml";
}
<style>
    @@import url(http://fonts.googleapis.com/css?family=Roboto:400,100);

    body {
        background: url(https://dl.dropboxusercontent.com/u/23299152/Wallpapers/wallpaper-22705.jpg) no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
        font-family: 'Roboto', sans-serif;
    }

    .login-card {
        padding: 40px;
        width: 274px;
        background-color: #F7F7F7;
        margin: 0 auto 10px;
        border-radius: 2px;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        overflow: hidden;
    }

        .login-card h1 {
            font-weight: 100;
            text-align: center;
            font-size: 2.3em;
        }

        .login-card input[type=submit] {
            width: 100%;
            display: block;
            margin-bottom: 10px;
            position: relative;
        }

        .login-card input[type=text], input[type=password] {
            height: 44px;
            font-size: 16px;
            width: 100%;
            margin-bottom: 10px;
            -webkit-appearance: none;
            background: #fff;
            border: 1px solid #d9d9d9;
            border-top: 1px solid #c0c0c0;
            /* border-radius: 2px; */
            padding: 0 8px;
            box-sizing: border-box;
            -moz-box-sizing: border-box;
        }

            .login-card input[type=text]:hover, input[type=password]:hover {
                border: 1px solid #b9b9b9;
                border-top: 1px solid #a0a0a0;
                -moz-box-shadow: inset 0 1px 2px rgba(0,0,0,0.1);
                -webkit-box-shadow: inset 0 1px 2px rgba(0,0,0,0.1);
                box-shadow: inset 0 1px 2px rgba(0,0,0,0.1);
            }

    .login {
        text-align: center;
        font-size: 14px;
        font-family: 'Arial', sans-serif;
        font-weight: 700;
        height: 36px;
        padding: 0 8px;
        /* border-radius: 3px; */
        /* -webkit-user-select: none;
    user-select: none; */
    }

    .login-submit {
        /* border: 1px solid #3079ed; */
        border: 0px;
        color: #fff;
        text-shadow: 0 1px rgba(0,0,0,0.1);
        background-color: #4d90fe;
        /* background-image: -webkit-gradient(linear, 0 0, 0 100%,   from(#4d90fe), to(#4787ed)); */
    }

        .login-submit:hover {
            /* border: 1px solid #2f5bb7; */
            border: 0px;
            text-shadow: 0 1px rgba(0,0,0,0.3);
            background-color: #357ae8;
            /* background-image: -webkit-gradient(linear, 0 0, 0 100%,   from(#4d90fe), to(#357ae8)); */
        }

    .login-card a {
        text-decoration: none;
        color: #666;
        font-weight: 400;
        text-align: center;
        display: inline-block;
        opacity: 0.6;
        transition: opacity ease 0.5s;
    }

        .login-card a:hover {
            opacity: 1;
        }

    .login-help {
        width: 100%;
        text-align: center;
        font-size: 12px;
    }
</style>
<div class="login-card">
    <h1>Result</h1><br>
    @using (Html.BeginForm("StateLogin", "State", FormMethod.Post))
    {


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <label class="text-info ">User Name:</label><br>
        <input type="text" name="User_Name" id="User_Name" class="form-control">
        <br />
        <label class="text-info">Password:</label><br>
        <input type="password" name="State_Password" id="State_Password" class="form-control">

        <input type="submit" name="submit" id="btnSubmit" class="btn btn-info btn-md" value="submit">

    }

    <div class="login-help">
        <a href="/CenterLogin/ForgotPassword">
            Forgot Password
        </a>
    </div>
</div>